### ISSUE TITLE
执行setOption的时候报错：TypeError: s is not a function

### ISSUE THREAD

**Issue by rockxsj** [ecomfe/echarts#1939]
TypeError: s is not a function
    at Object.i._render (http://127.0.0.1:8017/static/js/vendor/echarts/echarts.js:2:21179)
    at Object.i._setOption (http://127.0.0.1:8017/static/js/vendor/echarts/echarts.js:2:24540)
    at Object.i.setOption (http://127.0.0.1:8017/static/js/vendor/echarts/echarts.js:2:23981)
    at Component.echartsDraw (http://127.0.0.1:8017/static/js/service/chart.js?ver=1439997933720:145:31)
    at http://127.0.0.1:8017/static/js/service/api.js?ver=1439997933720:43:32
    at _fulfilled (http://127.0.0.1:8017/static/js/vendor/q.js?ver=1439997933720:794:54)
    at Promise.then.Q.nextTick.self.promiseDispatch.done (http://127.0.0.1:8017/static/js/vendor/q.js?ver=1439997933720:823:30)
    at Promise.promise.promiseDispatch (http://127.0.0.1:8017/static/js/vendor/q.js?ver=1439997933720:756:13)
    at http://127.0.0.1:8017/static/js/vendor/q.js?ver=1439997933720:564:44
    at MessagePort.flush (http://127.0.0.1:8017/static/js/vendor/q.js?ver=1439997933720:110:17)

相关代码如下：

     Component.prototype.echartsDraw = function(chartInstance, option) {
                console.log(chartInstance, option)
                chartInstance.setOption(option, true)
            }

其中chartInstance是echart的实例

之前用requireJs加载没有这个错误，但是各种404，搜了一下issue说换成esl，换了之后加载不会有问题了，不过这里报错了。。

**Comment by rockxsj** [comment]
浏览器是chrome    echarts是2.2.7

**Comment by rockxsj** [comment]
貌似找到原因了，esl加载模块的时候一定要在后面配个id，比如只能这样：
(function() {
    define(['echarts/echarts', 'lodash', 'echarts/chart/line', 'echarts/chart/bar', 'echarts/chart/map', 'echarts/chart/pie'], function(echarts, _, _line, _bar, _map, _pie) {

而不能：
(function() {
    define(['echarts/echarts', 'lodash', 'echarts/chart/line', 'echarts/chart/bar', 'echarts/chart/map', 'echarts/chart/pie'], function(echarts, _) {


请问是我用法有问题吗？？  这简直b了狗啊。。
