### ISSUE TITLE
IBM WebSphere 6.1下部署无法访问

### ISSUE THREAD

**Issue by caifrank** [ecomfe/echarts#3903]
#### 问题简述 (One-line summary)
echarts在WebSphere 6.1中部署使用出现以下错误：
 com.ibm.ws.jsp.JspCoreException: /com/rsc/rs/swsm/swsmqsz700/assets/js/echarts.min.js(11,9476) sun.io.MalformedInputException
	at com.ibm.ws.jsp.translator.document.Jsp2Dom.getJspDocumentAsJspPage(Jsp2Dom.java:290)
	at com.ibm.ws.jsp.translator.document.Jsp2Dom.getJspDocument(Jsp2Dom.java:170)
	at com.ibm.ws.jsp.translator.JspTranslator.<init>(JspTranslator.java:67)
	at com.ibm.ws.jsp.translator.JspTranslatorFactory.createTranslator(JspTranslatorFactory.java:112)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJsp(JspTranslatorUtil.java:180)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJspAndCompile(JspTranslatorUtil.java:83)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:349)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:317)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:226)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.handleRequest(AbstractJSPExtensionServletWrapper.java:131)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3107)
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:238)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:811)
	at com.ibm.ws.wswebcontainer.WebContainer.handleRequest(WebContainer.java:1425)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:92)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewInformation(HttpInboundLink.java:394)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:274)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:152)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:213)
	at com.ibm.io.async.AbstractAsyncFuture.fireCompletionActions(AbstractAsyncFuture.java:195)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:136)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:193)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:725)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:847)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1498)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.3
+ 浏览器类型和版本 (Browser version): 51.0.2704.106 (64-bit)
+ 操作系统类型和版本 (OS Version):Windows Server 2012

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
自行查找相关的答案，跟 echarts 无关
