### ISSUE TITLE
Error in loading echarts with latest build : zrUtil.eqNaN is not a function

### ISSUE THREAD

**Issue by mkmurali** [ecomfe/echarts#4719]
### One-line summary [问题简述]
Error in loading echarts with latest build

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: latest from Github as 17th December 2016
+ Browser version [浏览器类型和版本]: Chrome 54.0
+ OS Version [操作系统类型和版本]: Any OS

### Expected behaviour [期望结果]
Not able to load echarts

Uncaught TypeError: zrUtil.eqNaN is not a function
    at Object.axisHelper.getScaleExtent (https://echarts-muralicb.c9users.io/dist/echarts.js:26017:31)
    at axisHelper.niceScaleExtent (https://echarts-muralicb.c9users.io/dist/echarts.js:26036:34)
    at https://echarts-muralicb.c9users.io/dist/echarts.js:25493:14
    at each (https://echarts-muralicb.c9users.io/dist/echarts.js:3070:25)
    at Grid.gridProto.update (https://echarts-muralicb.c9users.io/dist/echarts.js:25492:10)
    at https://echarts-muralicb.c9users.io/dist/echarts.js:7005:46
    at Array.forEach (native)
    at Object.each (https://echarts-muralicb.c9users.io/dist/echarts.js:3060:18)
    at CoordinateSystemManager.update (https://echarts-muralicb.c9users.io/dist/echarts.js:7003:21)
    at ECharts.update (https://echarts-muralicb.c9users.io/dist/echarts.js:745:26)

**Comment by mkmurali** [comment]
Latest publicly available zrender (npm) is at 3.2.2, but missing a few updates that were referred in latest echarts code. So any local builds will fail until zrender is published. I have manually replaced the core/util.js in zrender with latest one on Github and that fixes the issue.

**Comment by pissang** [comment]
Did you build echarts by yourself ? If so, you need both echarts and zrender to be updated to the latest code.

**Comment by mkmurali** [comment]
Yes, I built echarts myself. If I completely replace zrender from github, running  into build issues. So I replaced just the util.js file for now to build and run successfully.

**Comment by pissang** [comment]
Great
