### ISSUE TITLE
ToolBox 点击还原出错

### ISSUE THREAD

**Issue by jiangmitiao** [ecomfe/echarts#5113]
### One-line summary [问题简述]
写了一个配置项，生成图表后，点击ToolBox还原按钮报错。
Uncaught Error
    at Object.assert (http://localhost:63342/echart/echarts.js:3334:20)
    at BrushController.enableBrush (http://localhost:63342/echart/echarts.js:43762:25)
    at BrushController.unmount (http://localhost:63342/echart/echarts.js:43913:19)
    at DataZoom.proto.remove (http://localhost:63342/echart/echarts.js:66357:32)
    at DataDiffer.process (http://localhost:63342/echart/echarts.js:65386:48)
    at DataDiffer.execute (http://localhost:63342/echart/echarts.js:22900:43)
    at ExtendedClass.render (http://localhost:63342/echart/echarts.js:65340:19)
    at ECharts.<anonymous> (http://localhost:63342/echart/echarts.js:1329:28)
    at Array.forEach (native)
    at each (http://localhost:63342/echart/echarts.js:3102:18)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.1
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
option = {
"color":["#c23531","#2f4554","#61a0a8","#d48265","#91c7ae","#749f83","#ca8622","#bda29a","#6e7074","#546570","#c4ccd3"],"legend":{"data":["展现","点击","访问","咨询","额外的测试","订单"],"show":true},"series":[{"data":[{"name":"展现","value":100},{"name":"点击","value":80},{"name":"访问","value":60},{"name":"咨询","value":40},{"name":"额外的测试","value":30},{"name":"订单","value":20}],"funnelAlign":"center","gap":0,"label":{"emphasis":{"show":true,"textStyle":{"color":"#000","fontFamily":"sans-serif","fontSize":12,"fontStyle":"normal","fontWeight":"normal"}},"normal":{"position":"outside","show":true,"textStyle":{"color":"#000","fontFamily":"sans-serif","fontSize":12,"fontStyle":"normal","fontWeight":"normal"}}},"max":100,"maxSize":"100%","min":0,"minSize":"0%","name":"漏斗模型","sort":"descending","type":"funnel"}],"textStyle":{"color":"#000","fontFamily":"sans-serif","fontSize":12,"fontStyle":"normal","fontWeight":"normal"},"title":{"itemGap":10,"show":true,"subtarget":"blank","subtext":"这是假的","subtextStyle":{"color":"#000","fontFamily":"sans-serif","fontSize":12,"fontStyle":"normal","fontWeight":"normal"},"target":"blank","text":"标题","textStyle":{"color":"#000","fontFamily":"sans-serif","fontSize":12,"fontStyle":"normal","fontWeight":"normal"}},"toolbox":{"feature":{"dataView":{"lang":["数据视图","关闭","刷新"],"readOnly":false,"show":true,"title":"数据视图"},"dataZoom":{"show":false},"magicType":{"show":true},"restore":{"show":true},"saveAsImage":{"show":true}},"itemGap":10,"itemSize":15,"layout":"horizontal","left":"right","show":true,"showTitle":true,"z":2,"zlevel":0},"tooltip":{"backgroundColor":"rgba(50,50,50,0.7)","borderColor":"#333","formatter":"{a} <br/>{b} : {c}%","show":true,"showContent":true,"trigger":"item","triggerOn":"mousemove"}
}

```

**Comment by 100pah** [comment]
暂时解决方式：把 toolbox.feature.dataZoom 这一段去掉试试看。

```js
    "toolbox": {
        "feature": {
            "dataView": {
                "lang": ["数据视图", "关闭", "刷新"],
                "readOnly": false,
                "show": true,
                "title": "数据视图"
            },
            // "dataZoom": {
            //     "show": false
            // },
            "magicType": {
                "show": true
            },
            "restore": {
                "show": true
            },
            "saveAsImage": {
                "show": true
            }
        },
        ...
}
