### ISSUE TITLE
Cannot read property 'toGlobalCoord' of undefined

### ISSUE THREAD

**Issue by sven0726** [ecomfe/echarts#5664]
### One-line summary [问题简述]
不断打出如下异常：
```
cartesianAxisHelper.js?ce88*:40 Uncaught TypeError: Cannot read property 'toGlobalCoord' of undefined
    at getZero (http://localhost:8001/9.9.js:74416:28)
    at Object.helper.layout (http://localhost:8001/9.9.js:74411:46)
    at ExtendedClass.render (http://localhost:8001/9.9.js:73112:47)
    at ECharts.<anonymous> (http://localhost:8001/9.9.js:45085:28)
    at Array.forEach (native)
    at each (http://localhost:8001/9.9.js:46913:18)
    at ECharts.doRender (http://localhost:8001/9.9.js:45083:10)
    at ECharts.update (http://localhost:8001/9.9.js:44520:23)
    at ECharts.prepareAndUpdate (http://localhost:8001/9.9.js:44653:39)
    at ECharts.echartsProto._onframe (http://localhost:8001/9.9.js:44047:45)
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:^3.5.4
+ Browser version [浏览器类型和版本]:Chrome  57.0.2987.133 (64-bit)
+ OS Version [操作系统类型和版本]: Mac pro 10.12.2

### ECharts option [ECharts配置项]

```javascript
option = {
    "tooltip": {
        "trigger": "axis",
        "axisPointer": {
            "type": "cross"
        }
    },
    "legend": {
        "data": []
    },
    "xAxis": [
        {
            "type": "category",
            "data": []
        }
    ],
    "yAxis": [],
    "series": []
}

```

**Comment by pissang** [comment]
你没有加 yAxis

**Comment by sven0726** [comment]
可以设置为空吧？初始化的时候

**Comment by pissang** [comment]
那建议 xAxis 也为空

**Comment by MrsKey** [comment]
@pissang echarts中能使用rem单位吗？

**Comment by sven0726** [comment]
@pissang   xAxis为空是可行的
